"""Author the website notices from verified contact details; no invented company facts."""
from html import escape
from pathlib import Path
import re

POLICY_TITLES = {
    'privacy': ('Privacy Policy', 'How AutixAI handles enquiries, local drafts, privacy choices and information requests.'),
    'terms': ('Website Terms', 'Using AutixAI, illustrative workflows, free audits and separately agreed paid projects.'),
    'refunds': ('Payments, Cancellation & Refunds', 'What to agree before a paid AutixAI project, and how to raise a cancellation or refund request.'),
    'cookies': ('Cookies & Privacy Choices', 'The storage used by this website and your control over optional analytics.'),
    'accessibility': ('Accessibility', 'Keyboard controls, motion choices and ways to report an accessibility problem to AutixAI.'),
}


def business_details(contact):
    e = lambda value: escape(str(value), quote=True)
    rows = [('Business brand', contact['name'])]
    for key, label in [('legalName', 'Legal / trading name'), ('city', 'Business location'), ('address', 'Business address')]:
        if contact.get(key):
            rows.append((label, contact[key]))
    details = ''.join(f'<div><dt>{e(label)}</dt><dd>{e(value)}</dd></div>' for label, value in rows)
    details += f'<div><dt>Contact</dt><dd><a href="tel:{e(contact["phone"])}">{e(contact["displayPhone"])}</a></dd></div>'
    if contact.get('email'):
        details += f'<div><dt>Email</dt><dd><a href="mailto:{e(contact["email"])}">{e(contact["email"])}</a></dd></div>'
    return f'<dl class="business-details">{details}</dl>'


def render_policy_pages(dist: Path, contact, version):
    e = lambda value: escape(str(value), quote=True)
    phone = f'<a href="tel:{e(contact["phone"])}">{e(contact["displayPhone"])}</a>'
    wa = f'https://wa.me/{contact["whatsapp"]}'
    contact_links = f'{phone} or <a href="{wa}" target="_blank" rel="noopener noreferrer">WhatsApp</a>'
    request_link = '<a href="/privacy/#privacy-request">prepare a privacy request</a>'
    identity = f'<section class="info-section" id="business-details"><h2>Who to contact</h2>{business_details(contact)}<p>AutixAI provides business automation and workflow integration services. The contracting party and any applicable registration, tax and billing details must be identified in the written proposal before a paid project begins.</p></section>'
    privacy_form = f'''<section class="info-section" id="privacy-request"><h2>Your information. Your request.</h2><p>Ask about information you sent us, request a copy or correction, request deletion, or ask us to stop promotional contact. You can also call {phone}. We may need to verify your connection to an enquiry before sharing or changing records. Do not send identity documents, passwords or customer records here.</p>
<form id="privacy-request-form" class="privacy-request-form" data-whatsapp="{e(contact['whatsapp'])}"><div class="form-field"><label for="privacy-kind">What would you like to do?</label><select id="privacy-kind" name="kind"><option>Delete my information</option><option>Access my information</option><option>Correct my information</option><option>Stop promotional contact</option><option>Privacy question</option><option>Accessibility help</option></select></div><div class="form-field"><label for="privacy-contact">Email or phone used to contact us</label><input id="privacy-contact" name="contact" required maxlength="120" autocomplete="off" aria-describedby="privacy-contact-hint"><span id="privacy-contact-hint" class="input-hint">One contact detail is enough to help locate your enquiry.</span></div><div class="form-field"><label for="privacy-details">Which enquiry or issue? <span class="optional">(optional)</span></label><textarea id="privacy-details" name="details" rows="3" maxlength="600" placeholder="For example: an automation enquiry sent in October."></textarea></div><p class="form-help">Preparing keeps this draft in the page. Opening WhatsApp shares it with WhatsApp; tap Send there to contact us. This does not subscribe you to marketing.</p><p id="privacy-request-error" class="field-error" role="alert" hidden></p><button type="submit" class="button" disabled>Prepare request</button><noscript><p>Use the phone or WhatsApp link above to make your request without JavaScript.</p></noscript><div id="privacy-request-result" class="inquiry-result" tabindex="-1" hidden><h3>Review your request</h3><pre id="privacy-request-preview"></pre><p role="status">Nothing has been sent. Review the draft, then send it in WhatsApp.</p><a id="privacy-request-send" class="button button-small" target="_blank" rel="noopener noreferrer">Review in WhatsApp & send</a><button id="privacy-request-clear" class="button button-small button-outline" type="button">Clear request</button></div></form></section>'''
    bodies = {
        'privacy': f'''{identity}
<section class="info-section"><h2>What we collect and why</h2><p>The enquiry form asks for your name, business, industry, your email, optional phone number, preferred contact method, type of automation, and the process you want to automate. Workload and current tools are optional. Information you choose to send is used to answer your enquiry, prepare an audit and discuss or deliver an agreed project. The privacy-request form asks only for a contact detail, request type and optional context. Avoid passwords, API keys, payment details, health information and confidential customer or employee records.</p><p>Preparing or sending an enquiry does not subscribe you to a mailing list. There is currently no newsletter sign-up or marketing-email service on this website. You can request that promotional contact stop using the request form below.</p></section>
<section class="info-section"><h2>You choose how to send</h2><p><span data-trust-inquiry-privacy>Submit Enquiry sends your reviewed contact and process details through AutixAI’s Vercel endpoint for validation and email delivery through FormSubmit. If FormSubmit rejects the server connection, your browser sends the validated details directly to its public form endpoint. Confirmation requires a delivery-service receipt; it does not guarantee inbox arrival. Chat on WhatsApp opens a draft you send yourself. No form details are saved in browser storage.</span> Opening WhatsApp passes the draft to WhatsApp; you review and tap Send there. Privacy requests use a separate WhatsApp draft route. The assistant can submit reviewed audit fields through the same enquiry endpoint, continue to the homepage form, or open a WhatsApp draft. An enquiry never automatically books a call or takes payment.</p><p>Reloading or leaving the page clears the website’s in-memory draft. Your browser may independently offer autofill or form restoration. Sending an enquiry creates separate records in the email or messaging service and the recipient’s records.</p></section>
<section class="info-section"><h2>The guided assistant and demos</h2><p>The assistant uses pre-written conversational branches, not a live AI model. Messages, selections and audit fields stay in the current page’s memory. Closing the panel retains them in that page; Reset, reload, navigation or closing the tab clears them. There is no chat history in browser storage and no AI provider or chat backend receives the conversation.</p><p>An assistant audit uses only the editable business, process, tool and contact fields you review. It does not include the full transcript. The calculator and workflow demos run locally and do not connect to your business tools.</p></section>
<section class="info-section"><h2>Cookies, optional analytics and hosting</h2><p>No advertising tracker or analytics service is currently enabled. Optional analytics events are blocked unless analytics is configured and you explicitly allow it. A consent choice, when optional analytics is enabled, is stored locally for up to 180 days; it contains only the choice, date and notice version. Enquiry, privacy-request and assistant text are never included. Decorative-motion choices last only in the current page.</p><p>Read <a href="/cookies/">Cookies & Privacy Choices</a> or <button type="button" class="inline-link" data-privacy-settings>open privacy settings</button>. Vercel hosts this site and may process request information such as IP addresses and logs under its <a href="https://vercel.com/legal/privacy-notice" target="_blank" rel="noopener noreferrer">Privacy Notice</a>. Fonts and website media are served with the site.</p></section>
<section class="info-section"><h2>External services and recipients</h2><p>FormSubmit processes the website enquiry fields and request metadata to deliver email to AutixAI’s Gmail inbox. It is contacted only when you choose Submit Enquiry; there is no embedded FormSubmit script or background submission. Read <a href="https://formsubmit.co/privacy.pdf" target="_blank" rel="noopener noreferrer">FormSubmit’s privacy information</a> and <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google’s Privacy Policy</a>. FormSubmit states that it keeps submissions awaiting form activation for up to 30 days. This provider-specific period is separate from AutixAI’s records.</p><p>WhatsApp applies its own <a href="https://www.whatsapp.com/legal/privacy-policies" target="_blank" rel="noopener noreferrer">privacy policies</a>. Instagram links open Instagram; the page does not embed an Instagram feed. A configured calendar link opens the named booking provider. These services may process data in other countries under their own terms. AutixAI does not control their separate records. Any additional service required for a paid project, its access and data responsibilities must be agreed in the project scope.</p></section>
<section class="info-section"><h2>Submission protection</h2><p>Our server validates inputs and rejects the hidden spam field. Vercel’s firewall limits repeated requests by IP. A server-side keyed fingerprint and delivery status help prevent repeat submissions for up to 24 hours on a warm function instance; raw contact details are not kept in that cache. Shared duplicate protection can be configured separately and is not currently active. Provider or network errors do not produce a success message. An uncertain delivery is held for review instead of automatically re-sent. A browser handoff is also held as uncertain on our server because FormSubmit provides no authenticated callback confirming its browser receipt. These controls do not protect the provider’s separate public form endpoint from direct submissions.</p></section><section class="info-section"><h2>Retention and deletion</h2><p>Drafts and chat have the short page-memory lifetime described above. Information you send to AutixAI is handled separately as enquiry, project or business records. Retention depends on the enquiry, the agreed project and applicable record-keeping obligations; a single fixed retention period for those records has not been set. You can ask what is held and request deletion below. We will review the request and explain any information that must be retained and why. A request to AutixAI does not delete the separate records of WhatsApp, Vercel or another provider.</p></section>
<section class="info-section"><h2>Children and sensitive information</h2><p>This website offers services to businesses and does not ask for dates of birth or children’s data. Do not include children’s personal information in enquiries, assistant messages or demo examples. If such information was sent by mistake, contact us using the request form. Any project involving children’s or sensitive data requires a separate assessment before access or development.</p></section>
{privacy_form}
<section class="info-section"><h2>Changes and project-specific information</h2><p>We update this notice when website behaviour changes. Project-specific data access, providers, retention and handover are agreed separately before implementation. The date above identifies this website notice.</p></section>''',
        'terms': f'''{identity}
<section class="info-section"><h2>Website information and examples</h2><p>This site describes AutixAI’s services and possible workflows. Demos, example automation cards and calculator results are illustrative unless explicitly identified as a verified project. They are not customer testimonials, guaranteed savings, a promise of staffing reductions or a guarantee that every platform supports a connection. AI outputs need appropriate review.</p></section>
<section class="info-section"><h2>Free audit and demo enquiries</h2><p>The initial automation audit is a free conversation and assessment. It does not include implementation, software subscriptions or a reserved meeting time. Preparing a request creates a draft only; you decide whether to send it. AutixAI arranges demo calls personally unless a separate booking service is shown.</p></section>
<section class="info-section"><h2>Paid work and clear costs</h2><p>A paid project requires a separate written agreement identifying the contracting party, scope, deliverables, price, applicable taxes, payment milestones, timeline, acceptance, ownership, data access and support. Any change in scope or cost needs agreement before the additional work starts. Third-party subscriptions, AI usage, messaging fees, hosting and support must be identified as included or separate. This website has no checkout, automatic billing or paid subscription enrolment.</p><p>See <a href="/refunds/">Payments, Cancellation & Refunds</a>. Cancellation and refund eligibility, any work already completed, committed third-party costs and the refund process must be agreed before payment. Nothing in these website notices removes rights that applicable law does not allow to be excluded.</p></section>
<section class="info-section"><h2>Responsible use and access</h2><p>Share only information you are authorised to provide. Do not submit passwords, keys, confidential records or children’s personal data in an initial enquiry or the guided assistant. Systems access, least-privilege permissions, human approval, testing and monitoring are agreed for the actual project. Do not use this website to interfere with other visitors, submit unlawful content or attempt unauthorised access.</p></section>
<section class="info-section"><h2>Content, assets and third-party services</h2><p>Website content and branding may be subject to intellectual-property rights. Font files are supplied under their included licences; those licences do not grant rights to AutixAI’s branding. Names of integration tools identify possible technologies, not endorsements or partnerships. WhatsApp, Instagram, booking providers and other platforms have their own terms and data practices. Availability, permissions, plans and features can change.</p></section>
<section class="info-section"><h2>Questions, accessibility and updates</h2><p>Contact us through {contact_links}. Read the <a href="/privacy/">Privacy Policy</a>, <a href="/cookies/">Cookies & Privacy Choices</a> and <a href="/accessibility/">Accessibility</a> page. We may update these website terms as the site changes; the date above identifies this version. Project agreements set the commercial terms of paid work.</p></section>''',
        'refunds': f'''<section class="info-section"><h2>Free means free</h2><p>The initial automation audit is free. This website does not collect payments, start paid subscriptions or automatically charge for an enquiry or demo call. Implementation and any paid support are quoted separately.</p></section>
<section class="info-section"><h2>Agree the terms before paying</h2><p>There is currently no standard refund window or blanket non-refundable-deposit rule published for all AutixAI projects. Before paying for a custom project, obtain a written proposal identifying the contracting party and covering:</p><ul class="policy-list"><li>Deliverables, milestones, acceptance and the total price, including applicable taxes.</li><li>Payment dates, deposit treatment and any recurring support charges.</li><li>How either party can cancel, and how completed or unfinished work is assessed.</li><li>Refund eligibility, calculation, payment method and expected processing time.</li><li>Third-party subscriptions or committed costs, who pays them and whose refund terms apply.</li><li>How scope changes, pauses and disputes will be handled.</li></ul><p>Do not rely on an assumed refund entitlement or an assumed no-refund rule. Ask for these terms to be clarified in the proposal before payment.</p></section>
<section class="info-section"><h2>Raise a cancellation or refund request</h2><p>Contact AutixAI through {contact_links}. Provide your project or invoice reference and a brief explanation; do not send full bank-account details, payment-card details or passwords. We will review the request against the agreed project terms, work status and any applicable rights, and discuss the next steps. A website enquiry alone does not cancel a third-party subscription.</p></section>
<section class="info-section"><h2>Third-party costs and your rights</h2><p>Provider fees can depend on message volume, AI usage, account plans and hosting. These costs must be disclosed before agreement; approved changes should be recorded in writing. A provider’s separate refund rules apply to its own charges. Nothing on this page excludes rights or remedies that applicable law does not allow to be excluded.</p></section>''',
        'cookies': '''<section class="info-section"><h2>What is active today?</h2><p>No optional analytics, advertising pixel, social-media embed or third-party chat SDK is currently enabled. Self-hosted fonts and media load with the page. Submit Enquiry contacts our same-origin Vercel endpoint without browser credentials; the server validates the request before contacting FormSubmit for email delivery. If FormSubmit rejects the server connection, the browser sends the validated details directly to FormSubmit. No embedded FormSubmit script is loaded. WhatsApp, Instagram and calendar links open external services only when selected; those services control their own storage after you open them.</p></section>
<section class="info-section"><h2>Browser storage and drafts</h2><ul class="policy-list"><li>Enquiry and privacy-request drafts: current page memory only; no localStorage, sessionStorage or application cookie.</li><li>Guided assistant: current page memory only. Reset or leaving the page clears it.</li><li>Decorative-motion choice: current page only; no persistent preference is stored.</li><li>Optional analytics consent: used only when optional analytics is enabled. The localStorage entry <code>autixai-privacy-choice</code> holds the choice, date and notice version for up to 180 days. It contains no chat or enquiry data.</li></ul><p>Hosting can involve request logs and infrastructure storage controlled by Vercel. See the <a href="/privacy/">Privacy Policy</a> for provider information.</p></section>
<section class="info-section"><h2>Your choice comes first</h2><p>If optional analytics is enabled in future, a notice will offer equally accessible allow and reject choices. Analytics events stay blocked until you allow them. You can reject optional analytics, change your choice or withdraw it in privacy settings. Rejecting does not block the website, assistant or enquiry form. Clearing browser storage, changing the notice version or reaching 180 days requires a new choice.</p><button class="button button-outline" type="button" data-privacy-settings>Open privacy settings</button><p class="info-note">Only fixed interaction names may be used by the optional analytics hook; form values, chat text and contact details are excluded. Any actual provider and its storage must be assessed and added to these notices before activation.</p></section>''',
        'accessibility': '''<section class="info-section"><h2>Using the site</h2><ul class="policy-list"><li>Use Tab and Shift+Tab to move between controls, and Enter or Space to activate them.</li><li>Use the “Skip to content” link to bypass navigation.</li><li>Use Escape to close the navigation or a dialog. Dialog controls keep keyboard focus within the open panel and return it on close.</li><li>Forms have visible labels, required-field instructions and written errors. Email is required for enquiries; phone is optional unless you choose a phone or WhatsApp reply.</li><li>The workflow film has controls, captions and a transcript.</li></ul></section>
<section class="info-section"><h2>Motion, zoom and readable content</h2><p>The site respects your device’s reduced-motion preference, including a flat mobile card layout. You can also pause decorative motion for the current page in privacy settings. User-started videos keep their own playback controls. Text and controls are designed to remain readable as the layout adapts to smaller screens and zoom.</p><button class="button button-outline" type="button" data-privacy-settings>Motion & privacy settings</button></section>
<section class="info-section"><h2>Report a barrier</h2><p>If a control, page or form is difficult to use, <a href="/privacy/?request=accessibility#privacy-request">prepare an accessibility help request</a> or use the phone link in the footer. Share the page, the action you tried and your device or assistive technology if useful. Avoid including sensitive personal information.</p><p>We review accessibility as the website changes. This page describes the available features; it is not a claim of complete WCAG conformance or certification.</p></section>''',
    }
    # Reuse the existing page shell; shared navigation and metadata are refreshed next.
    shell = (dist / 'privacy/index.html').read_text(encoding='utf-8')
    for slug, (title, description) in POLICY_TITLES.items():
        main = f'<main id="main" class="container info-main" tabindex="-1"><a class="back-link" href="/">Back to AutixAI</a><div class="info-hero"><h1>{e(title)}</h1><p>{e(description)}</p><small>Updated 8 October 2026</small></div>{bodies[slug]}</main>'
        html = re.sub(r'<main\b.*?</main>', lambda _: main, shell, count=1, flags=re.S)
        folder = dist / slug
        folder.mkdir(exist_ok=True)
        (folder / 'index.html').write_text(html, encoding='utf-8')
